### ISSUE TITLE
Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by ibrr1** [fpalomba/aDoctor#3]
When I run the tool on some apps i get the following error:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

an example is this app: https://github.com/zxing/zxing

any idea why is this happening?

**Comment by fpalomba** [comment]
Hi Ibrahim,  

I just tested the program using the zxing app as input.
Specifically, I cloned the app on my desktop and put the resulting folder as a subfolder of a folder called "Experiment". Then, I gave the "Experiment" folder path as input to aDoctor.

The process ended in less that 10 seconds without errors. Did you use the same setup?

Cheers,
Fabio

**Comment by ibrr1** [comment]
I was doing the same thing but i keep getting this error 
<img width="1034" alt="screen shot 2017-02-09 at 11 58 53 am" src="https://cloud.githubusercontent.com/assets/3493419/22793879/2693e380-eebf-11e6-8047-40f5eae91339.png">

This is a video shows what I was doing:
https://youtu.be/ZE0nV_lz2fw

**Comment by ibrr1** [comment]
I had the issue when I run on mac. I tried to run it on Windows machine and it run perfectly.
